//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExtensionsPage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtensionsPage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Beutl.Language.ExtensionsPage", typeof(ExtensionsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NoLogoImageAvailable {
            get {
                return ResourceManager.GetString("NoLogoImageAvailable", resourceCulture);
            }
        }
        
        public static string Package_Screenshots {
            get {
                return ResourceManager.GetString("Package_Screenshots", resourceCulture);
            }
        }
        
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        public static string Package_LatestRelease {
            get {
                return ResourceManager.GetString("Package_LatestRelease", resourceCulture);
            }
        }
        
        public static string Package_Tags {
            get {
                return ResourceManager.GetString("Package_Tags", resourceCulture);
            }
        }
        
        public static string Package_LatestVersion {
            get {
                return ResourceManager.GetString("Package_LatestVersion", resourceCulture);
            }
        }
        
        public static string Package_InstalledVersion {
            get {
                return ResourceManager.GetString("Package_InstalledVersion", resourceCulture);
            }
        }
        
        public static string OpenUrl_Title {
            get {
                return ResourceManager.GetString("OpenUrl_Title", resourceCulture);
            }
        }
        
        public static string OpenUrl_Content {
            get {
                return ResourceManager.GetString("OpenUrl_Content", resourceCulture);
            }
        }
        
        public static string Search_Packages {
            get {
                return ResourceManager.GetString("Search_Packages", resourceCulture);
            }
        }
        
        public static string Profile_PublishedPackages {
            get {
                return ResourceManager.GetString("Profile_PublishedPackages", resourceCulture);
            }
        }
        
        public static string RemoveFromLibrary {
            get {
                return ResourceManager.GetString("RemoveFromLibrary", resourceCulture);
            }
        }
        
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        public static string LocalPackages {
            get {
                return ResourceManager.GetString("LocalPackages", resourceCulture);
            }
        }
        
        public static string LocalPackage {
            get {
                return ResourceManager.GetString("LocalPackage", resourceCulture);
            }
        }
        
        public static string Could_not_find_a_package_from_remote {
            get {
                return ResourceManager.GetString("Could_not_find_a_package_from_remote", resourceCulture);
            }
        }
        
        public static string PackageInstaller {
            get {
                return ResourceManager.GetString("PackageInstaller", resourceCulture);
            }
        }
        
        public static string PackageInstaller_ScheduledInstallation {
            get {
                return ResourceManager.GetString("PackageInstaller_ScheduledInstallation", resourceCulture);
            }
        }
        
        public static string PackageInstaller_ScheduledUpdate {
            get {
                return ResourceManager.GetString("PackageInstaller_ScheduledUpdate", resourceCulture);
            }
        }
        
        public static string PackageInstaller_ScheduledUninstallation {
            get {
                return ResourceManager.GetString("PackageInstaller_ScheduledUninstallation", resourceCulture);
            }
        }
        
        public static string AuthorizationIsRequired {
            get {
                return ResourceManager.GetString("AuthorizationIsRequired", resourceCulture);
            }
        }
        
        public static string AnAccountIsRequiredToGetExtension {
            get {
                return ResourceManager.GetString("AnAccountIsRequiredToGetExtension", resourceCulture);
            }
        }
        
        public static string GotoSettings_Account {
            get {
                return ResourceManager.GetString("GotoSettings_Account", resourceCulture);
            }
        }
        
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string May_not_work_correctly_when_downgrading {
            get {
                return ResourceManager.GetString("May_not_work_correctly_when_downgrading", resourceCulture);
            }
        }
        
        public static string Package_SelectedRelease {
            get {
                return ResourceManager.GetString("Package_SelectedRelease", resourceCulture);
            }
        }
        
        public static string Release_TargetVersion {
            get {
                return ResourceManager.GetString("Release_TargetVersion", resourceCulture);
            }
        }
        
        public static string This_extension_does_not_support_your_Beutl_version {
            get {
                return ResourceManager.GetString("This_extension_does_not_support_your_Beutl_version", resourceCulture);
            }
        }
    }
}
