//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Beutl.Language.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ItemsSaved {
            get {
                return ResourceManager.GetString("ItemsSaved", resourceCulture);
            }
        }
        
        public static string ItemSaved {
            get {
                return ResourceManager.GetString("ItemSaved", resourceCulture);
            }
        }
        
        public static string OperationCouldNotBeExecuted {
            get {
                return ResourceManager.GetString("OperationCouldNotBeExecuted", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteThisDirectory {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisDirectory", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteThisFile {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisFile", resourceCulture);
            }
        }
        
        public static string DoYouWantToExcludeThisItemFromProject {
            get {
                return ResourceManager.GetString("DoYouWantToExcludeThisItemFromProject", resourceCulture);
            }
        }
        
        public static string CouldNotOpenFollowingFileWithExtension {
            get {
                return ResourceManager.GetString("CouldNotOpenFollowingFileWithExtension", resourceCulture);
            }
        }
        
        public static string CannotDisplayThisContext {
            get {
                return ResourceManager.GetString("CannotDisplayThisContext", resourceCulture);
            }
        }
        
        public static string ContextNotCreated {
            get {
                return ResourceManager.GetString("ContextNotCreated", resourceCulture);
            }
        }
        
        public static string EditorContextHasAlreadyBeenCreated {
            get {
                return ResourceManager.GetString("EditorContextHasAlreadyBeenCreated", resourceCulture);
            }
        }
        
        public static string NullWasSpecifiedForEditorContext {
            get {
                return ResourceManager.GetString("NullWasSpecifiedForEditorContext", resourceCulture);
            }
        }
        
        public static string PleaseEnterString {
            get {
                return ResourceManager.GetString("PleaseEnterString", resourceCulture);
            }
        }
        
        public static string InvalidString {
            get {
                return ResourceManager.GetString("InvalidString", resourceCulture);
            }
        }
        
        public static string MultipleTypesAreAvailable {
            get {
                return ResourceManager.GetString("MultipleTypesAreAvailable", resourceCulture);
            }
        }
        
        public static string AnimationIsEnabled {
            get {
                return ResourceManager.GetString("AnimationIsEnabled", resourceCulture);
            }
        }
        
        public static string ItAlreadyExists {
            get {
                return ResourceManager.GetString("ItAlreadyExists", resourceCulture);
            }
        }
        
        public static string ValueLessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ValueLessThanOrEqualToZero", resourceCulture);
            }
        }
        
        public static string ValueLessThanZero {
            get {
                return ResourceManager.GetString("ValueLessThanZero", resourceCulture);
            }
        }
        
        public static string CannotRenameBecauseConflicts {
            get {
                return ResourceManager.GetString("CannotRenameBecauseConflicts", resourceCulture);
            }
        }
        
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        public static string CouldNotOpenProject {
            get {
                return ResourceManager.GetString("CouldNotOpenProject", resourceCulture);
            }
        }
        
        public static string ApiErrorOccurred {
            get {
                return ResourceManager.GetString("ApiErrorOccurred", resourceCulture);
            }
        }
        
        public static string AnUnexpectedErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorHasOccurred", resourceCulture);
            }
        }
        
        public static string DoYouWantToLoadSideloadExtensions {
            get {
                return ResourceManager.GetString("DoYouWantToLoadSideloadExtensions", resourceCulture);
            }
        }
        
        public static string Unable_to_save_file {
            get {
                return ResourceManager.GetString("Unable_to_save_file", resourceCulture);
            }
        }
        
        public static string Failed_to_load_package {
            get {
                return ResourceManager.GetString("Failed_to_load_package", resourceCulture);
            }
        }
        
        public static string Failed_to_load_N_packages {
            get {
                return ResourceManager.GetString("Failed_to_load_N_packages", resourceCulture);
            }
        }
        
        public static string Could_not_load_scene {
            get {
                return ResourceManager.GetString("Could_not_load_scene", resourceCulture);
            }
        }
        
        public static string An_exception_occurred_during_audio_playback {
            get {
                return ResourceManager.GetString("An_exception_occurred_during_audio_playback", resourceCulture);
            }
        }
        
        public static string An_exception_occurred_while_drawing_frame {
            get {
                return ResourceManager.GetString("An_exception_occurred_while_drawing_frame", resourceCulture);
            }
        }
        
        public static string An_exception_occurred_during_output {
            get {
                return ResourceManager.GetString("An_exception_occurred_during_output", resourceCulture);
            }
        }
        
        public static string Ask_if_you_want_to_run_in_restricted_mode {
            get {
                return ResourceManager.GetString("Ask_if_you_want_to_run_in_restricted_mode", resourceCulture);
            }
        }
        
        public static string Looks_like_it_ended_with_an_error_last_time {
            get {
                return ResourceManager.GetString("Looks_like_it_ended_with_an_error_last_time", resourceCulture);
            }
        }
        
        public static string Changes_to_the_package_are_in_progress {
            get {
                return ResourceManager.GetString("Changes_to_the_package_are_in_progress", resourceCulture);
            }
        }
        
        public static string OpeningBeutl {
            get {
                return ResourceManager.GetString("OpeningBeutl", resourceCulture);
            }
        }
        
        public static string To_open_Beutl_close_Beutl_PackageTools {
            get {
                return ResourceManager.GetString("To_open_Beutl_close_Beutl_PackageTools", resourceCulture);
            }
        }
        
        public static string A_new_version_is_available {
            get {
                return ResourceManager.GetString("A_new_version_is_available", resourceCulture);
            }
        }
        
        public static string Could_not_restore_because_type_could_not_be_found {
            get {
                return ResourceManager.GetString("Could_not_restore_because_type_could_not_be_found", resourceCulture);
            }
        }
        
        public static string Must_upgrade_for_continued_use {
            get {
                return ResourceManager.GetString("Must_upgrade_for_continued_use", resourceCulture);
            }
        }
        
        public static string This_version_has_been_discontinued_for_compatibility_reasonsversion {
            get {
                return ResourceManager.GetString("This_version_has_been_discontinued_for_compatibility_reasonsversion", resourceCulture);
            }
        }
        
        public static string Double_click_to_hide_group {
            get {
                return ResourceManager.GetString("Double_click_to_hide_group", resourceCulture);
            }
        }
        
        public static string No_supported_extensions_were_found {
            get {
                return ResourceManager.GetString("No_supported_extensions_were_found", resourceCulture);
            }
        }
        
        public static string Property_is_unset {
            get {
                return ResourceManager.GetString("Property_is_unset", resourceCulture);
            }
        }
        
        public static string RightClickToShowMenu {
            get {
                return ResourceManager.GetString("RightClickToShowMenu", resourceCulture);
            }
        }
        
        public static string Failed_to_save_image {
            get {
                return ResourceManager.GetString("Failed_to_save_image", resourceCulture);
            }
        }
        
        public static string OpeningProject {
            get {
                return ResourceManager.GetString("OpeningProject", resourceCulture);
            }
        }
        
        public static string PleaseWaitAMoment {
            get {
                return ResourceManager.GetString("PleaseWaitAMoment", resourceCulture);
            }
        }
        
        public static string OpeningProjectMessage {
            get {
                return ResourceManager.GetString("OpeningProjectMessage", resourceCulture);
            }
        }
        
        public static string An_exception_occurred_while_saving_the_file {
            get {
                return ResourceManager.GetString("An_exception_occurred_while_saving_the_file", resourceCulture);
            }
        }
        
        public static string Files_are_saved_automatically {
            get {
                return ResourceManager.GetString("Files_are_saved_automatically", resourceCulture);
            }
        }
        
        public static string An_exception_occurred_while_parsing_the_SVG_path {
            get {
                return ResourceManager.GetString("An_exception_occurred_while_parsing_the_SVG_path", resourceCulture);
            }
        }
        
        public static string Signin_has_become_invalid {
            get {
                return ResourceManager.GetString("Signin has become invalid", resourceCulture);
            }
        }
        
        public static string File_is_not_selected {
            get {
                return ResourceManager.GetString("File_is_not_selected", resourceCulture);
            }
        }
        
        public static string CheckDifferentVersion_Title {
            get {
                return ResourceManager.GetString("CheckDifferentVersion_Title", resourceCulture);
            }
        }
        
        public static string CheckDifferentVersion_Content {
            get {
                return ResourceManager.GetString("CheckDifferentVersion_Content", resourceCulture);
            }
        }
        
        public static string ProjectVersionMismatch_Title {
            get {
                return ResourceManager.GetString("ProjectVersionMismatch_Title", resourceCulture);
            }
        }
        
        public static string ProjectVersionMismatch_Content {
            get {
                return ResourceManager.GetString("ProjectVersionMismatch_Content", resourceCulture);
            }
        }
        
        public static string Failed_to_load_metadata {
            get {
                return ResourceManager.GetString("Failed_to_load_metadata", resourceCulture);
            }
        }
        
        public static string Download_failed {
            get {
                return ResourceManager.GetString("Download_failed", resourceCulture);
            }
        }
        
        public static string Failed_to_load_script {
            get {
                return ResourceManager.GetString("Failed_to_load_script", resourceCulture);
            }
        }
        
        public static string The_application_needs_to_be_restarted {
            get {
                return ResourceManager.GetString("The_application_needs_to_be_restarted", resourceCulture);
            }
        }
        
        public static string Start_the_installer {
            get {
                return ResourceManager.GetString("Start_the_installer", resourceCulture);
            }
        }
        
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        public static string Download_is_complete {
            get {
                return ResourceManager.GetString("Download_is_complete", resourceCulture);
            }
        }
        
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        public static string Extraction_is_complete {
            get {
                return ResourceManager.GetString("Extraction_is_complete", resourceCulture);
            }
        }
        
        public static string An_error_has_occurred_Terminate_script {
            get {
                return ResourceManager.GetString("An_error_has_occurred_Terminate_script", resourceCulture);
            }
        }
        
        public static string Press_Enter_to_continue {
            get {
                return ResourceManager.GetString("Press_Enter_to_continue", resourceCulture);
            }
        }
        
        public static string Error_Update_directory_does_not_exist {
            get {
                return ResourceManager.GetString("Error_Update_directory_does_not_exist", resourceCulture);
            }
        }
        
        public static string Exit_the_application {
            get {
                return ResourceManager.GetString("Exit_the_application", resourceCulture);
            }
        }
        
        public static string Press_the_Enter_key_when_finished {
            get {
                return ResourceManager.GetString("Press_the_Enter_key_when_finished", resourceCulture);
            }
        }
        
        public static string Acquiring_lock {
            get {
                return ResourceManager.GetString("Acquiring_lock", resourceCulture);
            }
        }
        
        public static string Lock_acquired {
            get {
                return ResourceManager.GetString("Lock_acquired", resourceCulture);
            }
        }
        
        public static string Failed_to_acquire_lock {
            get {
                return ResourceManager.GetString("Failed_to_acquire_lock", resourceCulture);
            }
        }
        
        public static string Create_backup_of_current_application {
            get {
                return ResourceManager.GetString("Create_backup_of_current_application", resourceCulture);
            }
        }
        
        public static string Failed_to_create_backup {
            get {
                return ResourceManager.GetString("Failed_to_create_backup", resourceCulture);
            }
        }
        
        public static string Updating_files_in_place {
            get {
                return ResourceManager.GetString("Updating_files_in_place", resourceCulture);
            }
        }
        
        public static string Update_placement_failed_Restore_backup {
            get {
                return ResourceManager.GetString("Update_placement_failed_Restore_backup", resourceCulture);
            }
        }
        
        public static string The_update_has_been_completed {
            get {
                return ResourceManager.GetString("The_update_has_been_completed", resourceCulture);
            }
        }
        
        public static string Lock_released {
            get {
                return ResourceManager.GetString("Lock_released", resourceCulture);
            }
        }
        
        public static string Update_completed_yes_no {
            get {
                return ResourceManager.GetString("Update_completed_yes_no", resourceCulture);
            }
        }
        
        public static string Launch_the_application {
            get {
                return ResourceManager.GetString("Launch_the_application", resourceCulture);
            }
        }
        
        public static string Failed_to_change_application_execution_permissions {
            get {
                return ResourceManager.GetString("Failed_to_change_application_execution_permissions", resourceCulture);
            }
        }
        
        public static string The_application_execution_path_is_not_specified {
            get {
                return ResourceManager.GetString("The_application_execution_path_is_not_specified", resourceCulture);
            }
        }
        
        public static string The_application_was_not_launched {
            get {
                return ResourceManager.GetString("The_application_was_not_launched", resourceCulture);
            }
        }
        
        public static string Click_OK_after_completion {
            get {
                return ResourceManager.GetString("Click_OK_after_completion", resourceCulture);
            }
        }
        
        public static string Update_completed_Do_you_want_to_start_the_ߋn_application {
            get {
                return ResourceManager.GetString("Update_completed_Do_you_want_to_start_the_ߋn_application", resourceCulture);
            }
        }
        
        public static string Failed_to_restore_backup {
            get {
                return ResourceManager.GetString("Failed_to_restore_backup", resourceCulture);
            }
        }
        
        public static string Failed_to_delete_backup {
            get {
                return ResourceManager.GetString("Failed_to_delete_backup", resourceCulture);
            }
        }
        
        public static string Do_you_want_to_install {
            get {
                return ResourceManager.GetString("Do_you_want_to_install", resourceCulture);
            }
        }
    }
}
