//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.Language.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   A new version is available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string A_new_version_is_available {
            get {
                return ResourceManager.GetString("A_new_version_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred during audio playback. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string An_exception_occurred_during_audio_playback {
            get {
                return ResourceManager.GetString("An_exception_occurred_during_audio_playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred during output. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string An_exception_occurred_during_output {
            get {
                return ResourceManager.GetString("An_exception_occurred_during_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred while drawing the frame. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string An_exception_occurred_while_drawing_frame {
            get {
                return ResourceManager.GetString("An_exception_occurred_while_drawing_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred while loading the asset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string An_exception_occurred_while_loading_the_asset {
            get {
                return ResourceManager.GetString("An_exception_occurred_while_loading_the_asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred while saving the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string An_exception_occurred_while_saving_the_file {
            get {
                return ResourceManager.GetString("An_exception_occurred_while_saving_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation is enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnimationIsEnabled {
            get {
                return ResourceManager.GetString("AnimationIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnUnexpectedErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrorOccurred {
            get {
                return ResourceManager.GetString("ApiErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It seems that an error occurred and the program terminated last time.
        ///Do you want to run in restricted mode because the cause is unknown?
        ///
        ///Restricted mode does not load extensions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ask_if_you_want_to_run_in_restricted_mode {
            get {
                return ResourceManager.GetString("Ask_if_you_want_to_run_in_restricted_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot display this context. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotDisplayThisContext {
            get {
                return ResourceManager.GetString("CannotDisplayThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot rename from &quot;{0}&quot; to &quot;{1}&quot;
        ///because the new name conflicts with an existing folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotRenameBecauseConflicts {
            get {
                return ResourceManager.GetString("CannotRenameBecauseConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes to the package are in progress. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Changes_to_the_package_are_in_progress {
            get {
                return ResourceManager.GetString("Changes_to_the_package_are_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Context not created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextNotCreated {
            get {
                return ResourceManager.GetString("ContextNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load scene. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Could_not_load_scene {
            get {
                return ResourceManager.GetString("Could_not_load_scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not restore because the type could not be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Could_not_restore_because_type_could_not_be_found {
            get {
                return ResourceManager.GetString("Could_not_restore_because_type_could_not_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create an instance of View. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotCreateInstanceOfView {
            get {
                return ResourceManager.GetString("CouldNotCreateInstanceOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the following file with &apos;{0}&apos;.
        ///&apos;{1}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotOpenFollowingFileWithExtension {
            get {
                return ResourceManager.GetString("CouldNotOpenFollowingFileWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotOpenProject {
            get {
                return ResourceManager.GetString("CouldNotOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CountItems {
            get {
                return ResourceManager.GetString("CountItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double-click to hide group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Double_click_to_hide_group {
            get {
                return ResourceManager.GetString("Double_click_to_hide_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to add this item to current project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToAddThisItemToCurrentProject {
            get {
                return ResourceManager.GetString("DoYouWantToAddThisItemToCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this directory? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToDeleteThisDirectory {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToDeleteThisFile {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to exclude this item from the project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToExcludeThisItemFromProject {
            get {
                return ResourceManager.GetString("DoYouWantToExcludeThisItemFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to exclude this scene from the project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToExcludeThisSceneFromProject {
            get {
                return ResourceManager.GetString("DoYouWantToExcludeThisSceneFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to load sideload extensions? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToLoadSideloadExtensions {
            get {
                return ResourceManager.GetString("DoYouWantToLoadSideloadExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The editor context has already been created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditorContextHasAlreadyBeenCreated {
            get {
                return ResourceManager.GetString("EditorContextHasAlreadyBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load {0} packages. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed_to_load_N_packages {
            get {
                return ResourceManager.GetString("Failed_to_load_N_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load package. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed_to_load_package {
            get {
                return ResourceManager.GetString("Failed_to_load_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed_to_save_image {
            get {
                return ResourceManager.GetString("Failed_to_save_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files are saved automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Files_are_saved_automatically {
            get {
                return ResourceManager.GetString("Files_are_saved_automatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid choice. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Invalid_choice {
            get {
                return ResourceManager.GetString("Invalid_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidString {
            get {
                return ResourceManager.GetString("InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItAlreadyExists {
            get {
                return ResourceManager.GetString("ItAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} was saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSaved {
            get {
                return ResourceManager.GetString("ItemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemsSaved {
            get {
                return ResourceManager.GetString("ItemsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks like it ended with an error last time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Looks_like_it_ended_with_an_error_last_time {
            get {
                return ResourceManager.GetString("Looks_like_it_ended_with_an_error_last_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple types are available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultipleTypesAreAvailable {
            get {
                return ResourceManager.GetString("MultipleTypesAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must upgrade for continued use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Must_upgrade_for_continued_use {
            get {
                return ResourceManager.GetString("Must_upgrade_for_continued_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name cannot be left blank. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameCannotBeLeftBlank {
            get {
                return ResourceManager.GetString("NameCannotBeLeftBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No supported extensions were found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No_supported_extensions_were_found {
            get {
                return ResourceManager.GetString("No_supported_extensions_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null was specified for the editor context. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NullWasSpecifiedForEditorContext {
            get {
                return ResourceManager.GetString("NullWasSpecifiedForEditorContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening Beutl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpeningBeutl {
            get {
                return ResourceManager.GetString("OpeningBeutl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening a project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpeningProject {
            get {
                return ResourceManager.GetString("OpeningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening &apos;{0}&apos;.
        ///Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpeningProjectMessage {
            get {
                return ResourceManager.GetString("OpeningProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation could not be executed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationCouldNotBeExecuted {
            get {
                return ResourceManager.GetString("OperationCouldNotBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseEnterString {
            get {
                return ResourceManager.GetString("PleaseEnterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseWaitAMoment {
            get {
                return ResourceManager.GetString("PleaseWaitAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property is unset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_is_unset {
            get {
                return ResourceManager.GetString("Property_is_unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember this choice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberThisChoice {
            get {
                return ResourceManager.GetString("RememberThisChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right-click to show menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RightClickToShowMenu {
            get {
                return ResourceManager.GetString("RightClickToShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This version has been discontinued for compatibility reasons. Please upgrade to a newer version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string This_version_has_been_discontinued_for_compatibility_reasonsversion {
            get {
                return ResourceManager.GetString("This_version_has_been_discontinued_for_compatibility_reasonsversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To open Beutl, close Beutl.PackageTools. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string To_open_Beutl_close_Beutl_PackageTools {
            get {
                return ResourceManager.GetString("To_open_Beutl_close_Beutl_PackageTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to save file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unable_to_save_file {
            get {
                return ResourceManager.GetString("Unable_to_save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot specify a value less than or equal to 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueLessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ValueLessThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot specify a value less than to 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueLessThanZero {
            get {
                return ResourceManager.GetString("ValueLessThanZero", resourceCulture);
            }
        }
    }
}
