//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.Language.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Animation is enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnimationIsEnabled {
            get {
                return ResourceManager.GetString("AnimationIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot display this context. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotDisplayThisContext {
            get {
                return ResourceManager.GetString("CannotDisplayThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Context not created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextNotCreated {
            get {
                return ResourceManager.GetString("ContextNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create an instance of View. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotCreateInstanceOfView {
            get {
                return ResourceManager.GetString("CouldNotCreateInstanceOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the following file with &apos;{0}&apos;.
        ///&apos;{1}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotOpenFollowingFileWithExtension {
            get {
                return ResourceManager.GetString("CouldNotOpenFollowingFileWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CountItems {
            get {
                return ResourceManager.GetString("CountItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to add this item to current project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToAddThisItemToCurrentProject {
            get {
                return ResourceManager.GetString("DoYouWantToAddThisItemToCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this directory? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToDeleteThisDirectory {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToDeleteThisFile {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to exclude this item from the project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToExcludeThisItemFromProject {
            get {
                return ResourceManager.GetString("DoYouWantToExcludeThisItemFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to exclude this scene from the project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToExcludeThisSceneFromProject {
            get {
                return ResourceManager.GetString("DoYouWantToExcludeThisSceneFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The editor context has already been created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditorContextHasAlreadyBeenCreated {
            get {
                return ResourceManager.GetString("EditorContextHasAlreadyBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidString {
            get {
                return ResourceManager.GetString("InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} was saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSaved {
            get {
                return ResourceManager.GetString("ItemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemsSaved {
            get {
                return ResourceManager.GetString("ItemsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple types are available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultipleTypesAreAvailable {
            get {
                return ResourceManager.GetString("MultipleTypesAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null was specified for the editor context. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NullWasSpecifiedForEditorContext {
            get {
                return ResourceManager.GetString("NullWasSpecifiedForEditorContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation could not be executed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationCouldNotBeExecuted {
            get {
                return ResourceManager.GetString("OperationCouldNotBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseEnterString {
            get {
                return ResourceManager.GetString("PleaseEnterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember this choice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberThisChoice {
            get {
                return ResourceManager.GetString("RememberThisChoice", resourceCulture);
            }
        }
    }
}
