//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.Language.SettingsPage", typeof(SettingsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Accent color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add file extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add_file_extension {
            get {
                return ResourceManager.GetString("Add_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add property to hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddPropertyToHide {
            get {
                return ResourceManager.GetString("AddPropertyToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Editor Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string All_Editor_Extensions {
            get {
                return ResourceManager.GetString("All_Editor_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change account settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeAccountSettings {
            get {
                return ResourceManager.GetString("ChangeAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the primary properties to be hidden に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePrimaryPropertiesToBeHidden {
            get {
                return ResourceManager.GetString("ChangePrimaryPropertiesToBeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the visibility of this file to &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeVisibility {
            get {
                return ResourceManager.GetString("ChangeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy version info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyVersionInfo {
            get {
                return ResourceManager.GetString("CopyVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decoder Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DecoderPriority {
            get {
                return ResourceManager.GetString("DecoderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can change the priority order of decoders. The upper decoder has priority. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DecoderPriority_Description {
            get {
                return ResourceManager.GetString("DecoderPriority_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceInfomation {
            get {
                return ResourceManager.GetString("DeviceInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editor Extension Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Editor_Extension_Priority {
            get {
                return ResourceManager.GetString("Editor_Extension_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editor settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditorSettings {
            get {
                return ResourceManager.GetString("EditorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gpu Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GpuInfomation {
            get {
                return ResourceManager.GetString("GpuInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide primary properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HidePrimaryProperties {
            get {
                return ResourceManager.GetString("HidePrimaryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary properties can be set by adding &apos;Source Operation&apos;. Applies after the end of the program. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HidePrimaryProperties_Description {
            get {
                return ResourceManager.GetString("HidePrimaryProperties_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Higher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Higher {
            get {
                return ResourceManager.GetString("Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lower に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lower {
            get {
                return ResourceManager.GetString("Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make private に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakePrivate {
            get {
                return ResourceManager.GetString("MakePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make public に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakePublic {
            get {
                return ResourceManager.GetString("MakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenGL Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenGLVersion {
            get {
                return ResourceManager.GetString("OpenGLVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a file extension. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Please_enter_a_file_extension {
            get {
                return ResourceManager.GetString("Please_enter_a_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please read it carefully に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseReadItCarefully {
            get {
                return ResourceManager.GetString("PleaseReadItCarefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrimaryProperties {
            get {
                return ResourceManager.GetString("PrimaryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in via browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SignInViaBrowser {
            get {
                return ResourceManager.GetString("SignInViaBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in with your social accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SignInWith {
            get {
                return ResourceManager.GetString("SignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back up settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Storage_BackupSettings {
            get {
                return ResourceManager.GetString("Storage_BackupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Remaining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Storage_Remaining {
            get {
                return ResourceManager.GetString("Storage_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Storage_Used {
            get {
                return ResourceManager.GetString("Storage_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telemetry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry {
            get {
                return ResourceManager.GetString("Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIクライアント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Beutl_Api_Client {
            get {
                return ResourceManager.GetString("Telemetry_Beutl_Api_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Beutl_Application {
            get {
                return ResourceManager.GetString("Telemetry_Beutl_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Package Management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Beutl_PackageManagement {
            get {
                return ResourceManager.GetString("Telemetry_Beutl_PackageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display and operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Beutl_ViewTracking {
            get {
                return ResourceManager.GetString("Telemetry_Beutl_ViewTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To improve Beutl, we collect anonymous usage data.
        ///
        ///Below is some important information about this telemetry data.
        ///
        ///1. data to be collected
        ///Telemetry data includes information about the use of products and services.
        ///This includes application error logs, performance data, and usage statistics.
        ///
        ///2.Purpose of Data Collection
        ///Telemetry data is collected for a variety of purposes, including improving product and service quality, troubleshooting, monitoring security, and optimizing services.
        ///
        ///3. data s [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Description {
            get {
                return ResourceManager.GetString("Telemetry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collect API call times used by extension store and account functions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Description_Beutl_Api_Client {
            get {
                return ResourceManager.GetString("Telemetry_Description_Beutl_Api_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following information is collected to improve application performance
        ///Time the application was started, elapsed time of operation, and number of items retrieved by the API に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Description_Beutl_Application {
            get {
                return ResourceManager.GetString("Telemetry_Description_Beutl_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collect the time taken to install and load extensions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Description_Beutl_PackageManagement {
            get {
                return ResourceManager.GetString("Telemetry_Description_Beutl_PackageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collect what features users view or use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Description_Beutl_ViewTracking {
            get {
                return ResourceManager.GetString("Telemetry_Description_Beutl_ViewTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To improve Beutl, we collect anonymous usage data.
        ///
        ///Below is some important information about this telemetry data.
        ///
        ///1. data to be collected
        ///Telemetry data includes information about the use of products and services.
        ///This includes application error logs, performance data, and usage statistics.
        ///
        ///2.Purpose of Data Collection
        ///Telemetry data is collected for a variety of purposes, including improving product and service quality, troubleshooting, monitoring security, and optimizing services.
        ///
        ///3. data s [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_Description_For_Dialog {
            get {
                return ResourceManager.GetString("Telemetry_Description_For_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings about the data to be collected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Telemetry_ShortDescription {
            get {
                return ResourceManager.GetString("Telemetry_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following characters are not allowed (&quot; &gt; &lt; | : ? * \ /) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string The_following_characters_are_not_allowed {
            get {
                return ResourceManager.GetString("The_following_characters_are_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the theme of the app you want to display. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Theme_Tip {
            get {
                return ResourceManager.GetString("Theme_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file extension already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string This_file_extension_already_exists {
            get {
                return ResourceManager.GetString("This_file_extension_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use custom accent color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseCustomAccentColor {
            get {
                return ResourceManager.GetString("UseCustomAccentColor", resourceCulture);
            }
        }
    }
}
