//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddLayer {
            get {
                return ResourceManager.GetString("AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a setter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddSetter {
            get {
                return ResourceManager.GetString("AddSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to current project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddToCurrentProject {
            get {
                return ResourceManager.GetString("AddToCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlignmentX {
            get {
                return ResourceManager.GetString("AlignmentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlignmentY {
            get {
                return ResourceManager.GetString("AlignmentY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Angle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmap Effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitmapEffect {
            get {
                return ResourceManager.GetString("BitmapEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmap Interpolation Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitmapInterpolationMode {
            get {
                return ResourceManager.GetString("BitmapInterpolationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blend Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlendMode {
            get {
                return ResourceManager.GetString("BlendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blur に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Blur {
            get {
                return ResourceManager.GetString("Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BorderStyle {
            get {
                return ResourceManager.GetString("BorderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charactor Spacing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CharactorSpacing {
            get {
                return ResourceManager.GetString("CharactorSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseProject {
            get {
                return ResourceManager.GetString("CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Corner Radius に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_Completed {
            get {
                return ResourceManager.GetString("CreateAsset_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Example: large files such as assets in a package release. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_External_Example {
            get {
                return ResourceManager.GetString("CreateAsset_External_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The customer uploads the file to an external server
        ///and b-editor maintains the download URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_External_Tip {
            get {
                return ResourceManager.GetString("CreateAsset_External_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Example: Lightweight files such as images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_Internal_Example {
            get {
                return ResourceManager.GetString("CreateAsset_Internal_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload the file to the b-editor server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_Internal_Tip {
            get {
                return ResourceManager.GetString("CreateAsset_Internal_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performing an operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_PerformingAnOperation {
            get {
                return ResourceManager.GetString("CreateAsset_PerformingAnOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter at least one hash value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_PleaseEnterAtLeastOneHashValue {
            get {
                return ResourceManager.GetString("CreateAsset_PleaseEnterAtLeastOneHashValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_Title {
            get {
                return ResourceManager.GetString("CreateAsset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploading files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAsset_UploadingFiles {
            get {
                return ResourceManager.GetString("CreateAsset_UploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateNewScene {
            get {
                return ResourceManager.GetString("CreateNewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DestinationRect {
            get {
                return ResourceManager.GetString("DestinationRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop Shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DropShadow {
            get {
                return ResourceManager.GetString("DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DurationTime {
            get {
                return ResourceManager.GetString("DurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Easing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Easing {
            get {
                return ResourceManager.GetString("Easing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Easings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Easings {
            get {
                return ResourceManager.GetString("Easings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Animation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditAnimation {
            get {
                return ResourceManager.GetString("EditAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ellipse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclude に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Image Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FixImageSize {
            get {
                return ResourceManager.GetString("FixImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Family に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Weight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontWeight {
            get {
                return ResourceManager.GetString("FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Foreground に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FrameRate {
            get {
                return ResourceManager.GetString("FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gradient Origin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradientOrigin {
            get {
                return ResourceManager.GetString("GradientOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GradientStops {
            get {
                return ResourceManager.GetString("GradientStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Contrast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighContrast {
            get {
                return ResourceManager.GetString("HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inner Shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InnerShadow {
            get {
                return ResourceManager.GetString("InnerShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kernel Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KernelSize {
            get {
                return ResourceManager.GetString("KernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Links に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Margin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaskType {
            get {
                return ResourceManager.GetString("MaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move one back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveOneBack {
            get {
                return ResourceManager.GetString("MoveOneBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move one front に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveOneFront {
            get {
                return ResourceManager.GetString("MoveOneFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity Mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpacityMask {
            get {
                return ResourceManager.GetString("OpacityMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PickFont {
            get {
                return ResourceManager.GetString("PickFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Public に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radius に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Projects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove unavailable setters? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveUnavailableSetters {
            get {
                return ResourceManager.GetString("RemoveUnavailableSetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotation 3D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rotation3D {
            get {
                return ResourceManager.GetString("Rotation3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rounded rectangle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoundedRect {
            get {
                return ResourceManager.GetString("RoundedRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveOverWrite {
            get {
                return ResourceManager.GetString("SaveOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SceneFile {
            get {
                return ResourceManager.GetString("SceneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SceneSettings {
            get {
                return ResourceManager.GetString("SceneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select asset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAsset {
            get {
                return ResourceManager.GetString("SelectAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select image asset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectImageAsset {
            get {
                return ResourceManager.GetString("SelectImageAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shadow Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShadowOnly {
            get {
                return ResourceManager.GetString("ShadowOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sigma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sigma {
            get {
                return ResourceManager.GetString("Sigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skew に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Skew {
            get {
                return ResourceManager.GetString("Skew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceFile {
            get {
                return ResourceManager.GetString("SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SourceRect {
            get {
                return ResourceManager.GetString("SourceRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spread Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpreadMethod {
            get {
                return ResourceManager.GetString("SpreadMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream Operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StreamOperators {
            get {
                return ResourceManager.GetString("StreamOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stretch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stroke Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrokeWidth {
            get {
                return ResourceManager.GetString("StrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetType {
            get {
                return ResourceManager.GetString("TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thickness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Third Party Licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThirdPartyLicenses {
            get {
                return ResourceManager.GetString("ThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TileMode {
            get {
                return ResourceManager.GetString("TileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transform に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transform Origin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransformOrigin {
            get {
                return ResourceManager.GetString("TransformOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unimplemented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unimplemented {
            get {
                return ResourceManager.GetString("Unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
