//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New(_N).
        /// </summary>
        public static string AccessCreateNew {
            get {
                return ResourceManager.GetString("AccessCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit(_E).
        /// </summary>
        public static string AccessEdit {
            get {
                return ResourceManager.GetString("AccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(_F).
        /// </summary>
        public static string AccessFile {
            get {
                return ResourceManager.GetString("AccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help(_H).
        /// </summary>
        public static string AccessHelp {
            get {
                return ResourceManager.GetString("AccessHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open(_O).
        /// </summary>
        public static string AccessOpen {
            get {
                return ResourceManager.GetString("AccessOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output(_O).
        /// </summary>
        public static string AccessOut {
            get {
                return ResourceManager.GetString("AccessOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin(_X).
        /// </summary>
        public static string AccessPlugin {
            get {
                return ResourceManager.GetString("AccessPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project(_P).
        /// </summary>
        public static string AccessProject {
            get {
                return ResourceManager.GetString("AccessProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save(_S).
        /// </summary>
        public static string AccessSave {
            get {
                return ResourceManager.GetString("AccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool(_T).
        /// </summary>
        public static string AccessTool {
            get {
                return ResourceManager.GetString("AccessTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View(_V).
        /// </summary>
        public static string AccessView {
            get {
                return ResourceManager.GetString("AccessView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a clip.
        /// </summary>
        public static string AddClip {
            get {
                return ResourceManager.GetString("AddClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a effect.
        /// </summary>
        public static string AddEffect {
            get {
                return ResourceManager.GetString("AddEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a keyframe.
        /// </summary>
        public static string AddKeyframe {
            get {
                return ResourceManager.GetString("AddKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a scene.
        /// </summary>
        public static string AddScene {
            get {
                return ResourceManager.GetString("AddScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to list.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during rendering,
        ///so playback was stopped..
        /// </summary>
        public static string An_exception_was_thrown_during_rendering {
            get {
                return ResourceManager.GetString("An exception was thrown during rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during rendering, so the preview was temporarily stopped,
        ///and will be released after 5 seconds..
        /// </summary>
        public static string An_exception_was_thrown_during_rendering_preview {
            get {
                return ResourceManager.GetString("An exception was thrown during rendering preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file.
        /// </summary>
        public static string BackupFile {
            get {
                return ResourceManager.GetString("BackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup interval (min).
        /// </summary>
        public static string BackupInterval {
            get {
                return ResourceManager.GetString("BackupInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        public static string Clip {
            get {
                return ResourceManager.GetString("Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place a new clip because a clip already exists in the specified location..
        /// </summary>
        public static string ClipExistsInTheSpecifiedLocation {
            get {
                return ResourceManager.GetString("ClipExistsInTheSpecifiedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip height.
        /// </summary>
        public static string ClipHeight {
            get {
                return ResourceManager.GetString("ClipHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip infomation.
        /// </summary>
        public static string ClipInfo {
            get {
                return ResourceManager.GetString("ClipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette.
        /// </summary>
        public static string ColorPalette {
            get {
                return ResourceManager.GetString("ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can not be undone
        ///Do you want to perform the operation?.
        /// </summary>
        public static string CommandQ1 {
            get {
                return ResourceManager.GetString("CommandQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to json format.
        /// </summary>
        public static string ConvertJson {
            get {
                return ResourceManager.GetString("ConvertJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from backup file.
        /// </summary>
        public static string CreateFromBackup {
            get {
                return ResourceManager.GetString("CreateFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delet recorded commands.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled plugins.
        /// </summary>
        public static string DisabledPlugins {
            get {
                return ResourceManager.GetString("DisabledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a {0} or its child elements.
        /// </summary>
        public static string ErrorObjectViewer1 {
            get {
                return ResourceManager.GetString("ErrorObjectViewer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select {0}.
        /// </summary>
        public static string ErrorObjectViewer2 {
            get {
                return ResourceManager.GetString("ErrorObjectViewer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was thrown..
        /// </summary>
        public static string ExceptionWasThrown {
            get {
                return ResourceManager.GetString("ExceptionWasThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0}..
        /// </summary>
        public static string FailedToInstall {
            get {
                return ResourceManager.GetString("FailedToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed to load..
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save..
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg was not found.
        ///Do you want to install it?.
        /// </summary>
        public static string FFmpegNotFound {
            get {
                return ResourceManager.GetString("FFmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been saved.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate.
        /// </summary>
        public static string Framerate {
            get {
                return ResourceManager.GetString("Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the path.
        /// </summary>
        public static string GetPath {
            get {
                return ResourceManager.GetString("GetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image output.
        /// </summary>
        public static string ImageOutput {
            get {
                return ResourceManager.GetString("ImageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        public static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed plugins.
        /// </summary>
        public static string InstalledPlugins {
            get {
                return ResourceManager.GetString("InstalledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is checking..
        /// </summary>
        public static string IsChecking {
            get {
                return ResourceManager.GetString("IsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is downloading..
        /// </summary>
        public static string IsDownloading {
            get {
                return ResourceManager.GetString("IsDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is extracted and placed..
        /// </summary>
        public static string IsExtractedAndPlaced {
            get {
                return ResourceManager.GetString("IsExtractedAndPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is loading..
        /// </summary>
        public static string IsLoading {
            get {
                return ResourceManager.GetString("IsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to use.
        /// </summary>
        public static string LearnHowToUse {
            get {
                return ResourceManager.GetString("LearnHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this plugin next time.
        /// </summary>
        public static string LoadPlugin {
            get {
                return ResourceManager.GetString("LoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory release.
        /// </summary>
        public static string MemoryRelease {
            get {
                return ResourceManager.GetString("MemoryRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to end.
        /// </summary>
        public static string MoveToEnd {
            get {
                return ResourceManager.GetString("MoveToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to the next frame.
        /// </summary>
        public static string MoveToNextFrame {
            get {
                return ResourceManager.GetString("MoveToNextFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to previous frame.
        /// </summary>
        public static string MoveToPreviousFrame {
            get {
                return ResourceManager.GetString("MoveToPreviousFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to the specified frame..
        /// </summary>
        public static string MoveToSpecifiedFrame {
            get {
                return ResourceManager.GetString("MoveToSpecifiedFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to top.
        /// </summary>
        public static string MoveToTop {
            get {
                return ResourceManager.GetString("MoveToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        public static string NewVersionIsAvailable {
            get {
                return ResourceManager.GetString("NewVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectViewer.
        /// </summary>
        public static string ObjectViewer {
            get {
                return ResourceManager.GetString("ObjectViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAL was not found.
        ///Please install it..
        /// </summary>
        public static string OpenALNotFound {
            get {
                return ResourceManager.GetString("OpenALNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the directory where this project file is located.
        /// </summary>
        public static string OpenProjectDirectory {
            get {
                return ResourceManager.GetString("OpenProjectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the repository for this software.
        /// </summary>
        public static string OpenThisRepository {
            get {
                return ResourceManager.GetString("OpenThisRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization.
        /// </summary>
        public static string Optimization {
            get {
                return ResourceManager.GetString("Optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} plugins have been added.
        ///Please select the plugin you want to load.
        /// </summary>
        public static string PluginsAddedMessage {
            get {
                return ResourceManager.GetString("PluginsAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file.
        /// </summary>
        public static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide property.
        /// </summary>
        public static string PropertyShowHide {
            get {
                return ResourceManager.GetString("PropertyShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value of {0} or greater..
        /// </summary>
        public static string RangeAbove {
            get {
                return ResourceManager.GetString("RangeAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent fonts.
        /// </summary>
        public static string RecentFonts {
            get {
                return ResourceManager.GetString("RecentFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samplingrate.
        /// </summary>
        public static string Samplingrate {
            get {
                return ResourceManager.GetString("Samplingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder.
        /// </summary>
        public static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the current scene.
        /// </summary>
        public static string SceneSettings {
            get {
                return ResourceManager.GetString("SceneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback(Open an Issue on GitHub).
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate.
        /// </summary>
        public static string Separate {
            get {
                return ResourceManager.GetString("Separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup is complete..
        /// </summary>
        public static string SetupComplete {
            get {
                return ResourceManager.GetString("SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show start window..
        /// </summary>
        public static string ShowStartWindow {
            get {
                return ResourceManager.GetString("ShowStartWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some functions are not available..
        /// </summary>
        public static string SomeFunctionsAreNotAvailable_ {
            get {
                return ResourceManager.GetString("SomeFunctionsAreNotAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start frame.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project..
        /// </summary>
        public static string ThereIsNoProject {
            get {
                return ResourceManager.GetString("ThereIsNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists..
        /// </summary>
        public static string ThisNameAlreadyExists {
            get {
                return ResourceManager.GetString("ThisNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is latest..
        /// </summary>
        public static string ThisSoftwareIsLatest {
            get {
                return ResourceManager.GetString("ThisSoftwareIsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide timeline.
        /// </summary>
        public static string TimelineShowHide {
            get {
                return ResourceManager.GetString("TimelineShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to create a project, click New..
        /// </summary>
        public static string ToCreateProjectClickNew {
            get {
                return ResourceManager.GetString("ToCreateProjectClickNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t load this plugin next time.
        /// </summary>
        public static string UnloadPlugin {
            get {
                return ResourceManager.GetString("UnloadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use automatic backups.
        /// </summary>
        public static string UseAutoBackup {
            get {
                return ResourceManager.GetString("UseAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dark mode.
        /// </summary>
        public static string UseDarkMode {
            get {
                return ResourceManager.GetString("UseDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video output.
        /// </summary>
        public static string VideoOutput {
            get {
                return ResourceManager.GetString("VideoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of 1 frame.
        /// </summary>
        public static string WidthOf1Frame {
            get {
                return ResourceManager.GetString("WidthOf1Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
