using Beutl.Services;

namespace Beutl.HeadlessUITests;

[TestFixture]
public sealed class FlatpakBundleMetadataTests
{
    [OneTimeSetUp]
    public void RequireLinuxGLib()
    {
        if (!OperatingSystem.IsLinux()) Assert.Ignore("Uses the GLib library supplied by the Flatpak runtime.");
    }

    // The fixtures contain only an 'echo fixture' shell script (or a runtime marker).
    // They were generated by flatpak build-export --disable-sandbox and build-bundle
    // with the app ID, architecture, branch, and --runtime variations below.
    [TestCase("beutl", "app/net.beditor.Beutl/x86_64/master")]
    [TestCase("other-app", "app/org.example.Other/x86_64/master")]
    [TestCase("other-arch", "app/net.beditor.Beutl/aarch64/master")]
    [TestCase("other-branch", "app/net.beditor.Beutl/x86_64/stable")]
    [TestCase("runtime", "runtime/net.beditor.Beutl/x86_64/master")]
    public void ReadRef_ReadsTheActualBundleIdentityWithoutChangingTheFile(string fixture, string expected)
    {
        byte[] data = ReadFixture(fixture);
        WithBundle(data, path =>
        {
            Assert.That(FlatpakBundleMetadata.ReadRef(path), Is.EqualTo(expected));
            Assert.That(File.ReadAllBytes(path), Is.EqualTo(data));
        });
    }

    [TestCase(0)]
    [TestCase(8)]
    [TestCase(32)]
    [TestCase(500)]
    public void ReadRef_RejectsTruncatedBundles(int length)
    {
        byte[] data = ReadFixture("beutl");
        WithBundle(data[..length], path => Assert.That(FlatpakBundleMetadata.ReadRef(path), Is.Null));
    }

    [Test]
    public void ReadRef_DoesNotAcceptAReferenceEmbeddedInPlainText()
    {
        WithBundle("app/net.beditor.Beutl/x86_64/master"u8.ToArray(),
            path => Assert.That(FlatpakBundleMetadata.ReadRef(path), Is.Null));
    }

    private static byte[] ReadFixture(string name)
    {
        using var source = typeof(FlatpakBundleMetadataTests).Assembly.GetManifestResourceStream(
            $"Beutl.HeadlessUITests.Assets.Flatpak.{name}.flatpak")!;
        using var output = new MemoryStream();
        source.CopyTo(output);
        return output.ToArray();
    }

    private static void WithBundle(byte[] data, Action<string> action)
    {
        string path = Path.Combine(Path.GetTempPath(), "beutl-bundle-metadata-" + Guid.NewGuid().ToString("N") + ".flatpak");
        try
        {
            File.WriteAllBytes(path, data);
            action(path);
        }
        finally { File.Delete(path); }
    }
}
