//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Properties.CommandName", typeof(CommandName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the clip.
        /// </summary>
        internal static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut out the clip.
        /// </summary>
        internal static string CUT {
            get {
                return ResourceManager.GetString("CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to end.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image output.
        /// </summary>
        internal static string IMAGE_OUT {
            get {
                return ResourceManager.GetString("IMAGE_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a project.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to next frame.
        /// </summary>
        internal static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the project.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the clip.
        /// </summary>
        internal static string PASTE {
            get {
                return ResourceManager.GetString("PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        internal static string PLAY_PAUSE {
            get {
                return ResourceManager.GetString("PLAY_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to previous frame.
        /// </summary>
        internal static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string REDO {
            get {
                return ResourceManager.GetString("REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the clip.
        /// </summary>
        internal static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a project.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode to top.
        /// </summary>
        internal static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UNDO {
            get {
                return ResourceManager.GetString("UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video output.
        /// </summary>
        internal static string VIDEO_OUT {
            get {
                return ResourceManager.GetString("VIDEO_OUT", resourceCulture);
            }
        }
    }
}
