//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new clip.
        /// </summary>
        public static string AddClip {
            get {
                return ResourceManager.GetString("AddClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new effect.
        /// </summary>
        public static string AddEffect {
            get {
                return ResourceManager.GetString("AddEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a keyframe.
        /// </summary>
        public static string AddKeyframe {
            get {
                return ResourceManager.GetString("AddKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new scene.
        /// </summary>
        public static string AddScene {
            get {
                return ResourceManager.GetString("AddScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to list.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust length.
        /// </summary>
        public static string AdjustLengthOfClip {
            get {
                return ResourceManager.GetString("AdjustLengthOfClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already cancelled..
        /// </summary>
        public static string AlreadyCancelled {
            get {
                return ResourceManager.GetString("AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during rendering,
        ///so playback was stopped..
        /// </summary>
        public static string An_exception_was_thrown_during_rendering {
            get {
                return ResourceManager.GetString("An exception was thrown during rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during rendering, so the preview was temporarily stopped,
        ///and will be released after 5 seconds..
        /// </summary>
        public static string An_exception_was_thrown_during_rendering_preview {
            get {
                return ResourceManager.GetString("An exception was thrown during rendering preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly File.
        /// </summary>
        public static string AssemblyFile {
            get {
                return ResourceManager.GetString("AssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file.
        /// </summary>
        public static string AudioFile {
            get {
                return ResourceManager.GetString("AudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files.
        /// </summary>
        public static string AudioFiles {
            get {
                return ResourceManager.GetString("AudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file.
        /// </summary>
        public static string BackupFile {
            get {
                return ResourceManager.GetString("BackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup interval (min).
        /// </summary>
        public static string BackupInterval {
            get {
                return ResourceManager.GetString("BackupInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind.
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change failed..
        /// </summary>
        public static string ChangeFailed {
            get {
                return ResourceManager.GetString("ChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change succeeded..
        /// </summary>
        public static string ChangeSucceeded {
            get {
                return ResourceManager.GetString("ChangeSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkered (Dark).
        /// </summary>
        public static string CheckDark {
            get {
                return ResourceManager.GetString("CheckDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkered (Light).
        /// </summary>
        public static string CheckLight {
            get {
                return ResourceManager.GetString("CheckLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        public static string Clip {
            get {
                return ResourceManager.GetString("Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place a new clip because a clip already exists in the specified location..
        /// </summary>
        public static string ClipExistsInTheSpecifiedLocation {
            get {
                return ResourceManager.GetString("ClipExistsInTheSpecifiedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip height.
        /// </summary>
        public static string ClipHeight {
            get {
                return ResourceManager.GetString("ClipHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of the clip.
        /// </summary>
        public static string ClipId {
            get {
                return ResourceManager.GetString("ClipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip infomation.
        /// </summary>
        public static string ClipInfo {
            get {
                return ResourceManager.GetString("ClipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec.
        /// </summary>
        public static string Codec {
            get {
                return ResourceManager.GetString("Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette.
        /// </summary>
        public static string ColorPalette {
            get {
                return ResourceManager.GetString("ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can not be undone
        ///Do you want to perform the operation?.
        /// </summary>
        public static string CommandQ1 {
            get {
                return ResourceManager.GetString("CommandQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component is extracted and placed..
        /// </summary>
        public static string ComponentIsExtractedAndPlaced {
            get {
                return ResourceManager.GetString("ComponentIsExtractedAndPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container format.
        /// </summary>
        public static string ContainerFormat {
            get {
                return ResourceManager.GetString("ContainerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to json format.
        /// </summary>
        public static string ConvertJson {
            get {
                return ResourceManager.GetString("ConvertJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert video.
        /// </summary>
        public static string ConvertVideo {
            get {
                return ResourceManager.GetString("ConvertVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the ID.
        /// </summary>
        public static string CopyID {
            get {
                return ResourceManager.GetString("CopyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the package..
        /// </summary>
        public static string CouldNotCreatePackage {
            get {
                return ResourceManager.GetString("CouldNotCreatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from backup file.
        /// </summary>
        public static string CreateFromBackup {
            get {
                return ResourceManager.GetString("CreateFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a plugin package.
        /// </summary>
        public static string CreatePluginPackage {
            get {
                return ResourceManager.GetString("CreatePluginPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a scene.
        /// </summary>
        public static string CreateScene {
            get {
                return ResourceManager.GetString("CreateScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delet recorded commands.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the required components..
        /// </summary>
        public static string DownloadingRequiredComponents {
            get {
                return ResourceManager.GetString("DownloadingRequiredComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect file.
        /// </summary>
        public static string EffectFile {
            get {
                return ResourceManager.GetString("EffectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder.
        /// </summary>
        public static string Encoder {
            get {
                return ResourceManager.GetString("Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoder is not set.
        ///After the encoder is set, the detailed settings will be displayed..
        /// </summary>
        public static string EncoderIsNotSet {
            get {
                return ResourceManager.GetString("EncoderIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder not found..
        /// </summary>
        public static string EncoderNotFound {
            get {
                return ResourceManager.GetString("EncoderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder settings.
        /// </summary>
        public static string EncoderSettings {
            get {
                return ResourceManager.GetString("EncoderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a {0} or its child elements.
        /// </summary>
        public static string ErrorObjectViewer1 {
            get {
                return ResourceManager.GetString("ErrorObjectViewer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select {0}.
        /// </summary>
        public static string ErrorObjectViewer2 {
            get {
                return ResourceManager.GetString("ErrorObjectViewer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was thrown..
        /// </summary>
        public static string ExceptionWasThrown {
            get {
                return ResourceManager.GetString("ExceptionWasThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0}..
        /// </summary>
        public static string FailedTo {
            get {
                return ResourceManager.GetString("FailedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0}..
        /// </summary>
        public static string FailedToInstall {
            get {
                return ResourceManager.GetString("FailedToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed to load..
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save..
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been saved.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate.
        /// </summary>
        public static string Framerate {
            get {
                return ResourceManager.GetString("Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the path.
        /// </summary>
        public static string GetPath {
            get {
                return ResourceManager.GetString("GetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to main window.
        /// </summary>
        public static string GoToMainWindow {
            get {
                return ResourceManager.GetString("GoToMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics profile.
        /// </summary>
        public static string GraphicsProfile {
            get {
                return ResourceManager.GetString("GraphicsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenGL: 
        ///- Renders using &quot;OpenGL&quot;.
        ///
        ///Skia:
        ///- Renders using &quot;Skia&quot;.
        ///- 3D drawing is not supported.
        ///- Materials, lights, and cameras are not available.
        ///
        ///Direct3D 11:
        ///- Renders using &quot;Direct3D 11&quot;.
        ///- For Windows.
        ///- The lighting is not yet implemented.
        ///
        ///Metal:
        ///- Renders using &quot;Metal&quot;.
        ///- For macOS.
        ///- The lighting is not yet implemented.
        ///
        ///Vulkan: 
        ///- Renders using &quot;Vulkan&quot;.
        ///- The lighting is not yet implemented..
        /// </summary>
        public static string GraphicsProfileDescription {
            get {
                return ResourceManager.GetString("GraphicsProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file.
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image output.
        /// </summary>
        public static string ImageOutput {
            get {
                return ResourceManager.GetString("ImageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        public static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id.
        ///GUID and UUID can be used for Id..
        /// </summary>
        public static string InvalidIdCanUseGUIDAndUUID {
            get {
                return ResourceManager.GetString("InvalidIdCanUseGUIDAndUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is checking..
        /// </summary>
        public static string IsChecking {
            get {
                return ResourceManager.GetString("IsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is loading..
        /// </summary>
        public static string IsLoading {
            get {
                return ResourceManager.GetString("IsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key bindings.
        /// </summary>
        public static string KeyBindings {
            get {
                return ResourceManager.GetString("KeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to use.
        /// </summary>
        public static string LearnHowToUse {
            get {
                return ResourceManager.GetString("LearnHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine translation.
        /// </summary>
        public static string MachineTranslation {
            get {
                return ResourceManager.GetString("MachineTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Plugins.
        /// </summary>
        public static string ManagePlugins {
            get {
                return ResourceManager.GetString("ManagePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory release.
        /// </summary>
        public static string MemoryRelease {
            get {
                return ResourceManager.GetString("MemoryRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to end.
        /// </summary>
        public static string MoveToEnd {
            get {
                return ResourceManager.GetString("MoveToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to the next frame.
        /// </summary>
        public static string MoveToNextFrame {
            get {
                return ResourceManager.GetString("MoveToNextFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to previous frame.
        /// </summary>
        public static string MoveToPreviousFrame {
            get {
                return ResourceManager.GetString("MoveToPreviousFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to the specified frame..
        /// </summary>
        public static string MoveToSpecifiedFrame {
            get {
                return ResourceManager.GetString("MoveToSpecifiedFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to top.
        /// </summary>
        public static string MoveToTop {
            get {
                return ResourceManager.GetString("MoveToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clip is selected..
        /// </summary>
        public static string NoClipIsSelected {
            get {
                return ResourceManager.GetString("NoClipIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported formats..
        /// </summary>
        public static string NotSupportedFormats {
            get {
                return ResourceManager.GetString("NotSupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object file.
        /// </summary>
        public static string ObjectFile {
            get {
                return ResourceManager.GetString("ObjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAL was not found.
        ///Please install it..
        /// </summary>
        public static string OpenALNotFound {
            get {
                return ResourceManager.GetString("OpenALNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operate.
        /// </summary>
        public static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization.
        /// </summary>
        public static string Optimization {
            get {
                return ResourceManager.GetString("Optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory.
        /// </summary>
        public static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package source.
        /// </summary>
        public static string PackageSource {
            get {
                return ResourceManager.GetString("PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password are not matching.
        /// </summary>
        public static string PasswordAreNotMatching {
            get {
                return ResourceManager.GetString("PasswordAreNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0}..
        /// </summary>
        public static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file.
        /// </summary>
        public static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide property.
        /// </summary>
        public static string PropertyShowHide {
            get {
                return ResourceManager.GetString("PropertyShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value of {0} or greater..
        /// </summary>
        public static string RangeAbove {
            get {
                return ResourceManager.GetString("RangeAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent fonts.
        /// </summary>
        public static string RecentFonts {
            get {
                return ResourceManager.GetString("RecentFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samplingrate.
        /// </summary>
        public static string Samplingrate {
            get {
                return ResourceManager.GetString("Samplingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder.
        /// </summary>
        public static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save full path.
        /// </summary>
        public static string SaveFullPath {
            get {
                return ResourceManager.GetString("SaveFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the path relative to the selected path from the project.
        /// </summary>
        public static string SavePathRelativeToSelectedPathFromProject {
            get {
                return ResourceManager.GetString("SavePathRelativeToSelectedPathFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the current scene.
        /// </summary>
        public static string SceneSettings {
            get {
                return ResourceManager.GetString("SceneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate.
        /// </summary>
        public static string Separate {
            get {
                return ResourceManager.GetString("Separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set maximum frame.
        /// </summary>
        public static string SetMaximumFrame {
            get {
                return ResourceManager.GetString("SetMaximumFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Update Notes.
        /// </summary>
        public static string ShortUpdateNote {
            get {
                return ResourceManager.GetString("ShortUpdateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show start window..
        /// </summary>
        public static string ShowStartWindow {
            get {
                return ResourceManager.GetString("ShowStartWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some functions are not available..
        /// </summary>
        public static string SomeFunctionsAreNotAvailable_ {
            get {
                return ResourceManager.GetString("SomeFunctionsAreNotAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified clip is not found..
        /// </summary>
        public static string SpecifiedClipIsNotFound {
            get {
                return ResourceManager.GetString("SpecifiedClipIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start frame.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be applied after restarting..
        /// </summary>
        public static string TheChangesWillBeAppliedAfterRestarting {
            get {
                return ResourceManager.GetString("TheChangesWillBeAppliedAfterRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project..
        /// </summary>
        public static string ThereIsNoProject {
            get {
                return ResourceManager.GetString("ThereIsNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file cannot be converted..
        /// </summary>
        public static string ThisFileCannotBeConverted {
            get {
                return ResourceManager.GetString("ThisFileCannotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item cannot be changed..
        /// </summary>
        public static string ThisItemCannotBeChanged {
            get {
                return ResourceManager.GetString("ThisItemCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists..
        /// </summary>
        public static string ThisNameAlreadyExists {
            get {
                return ResourceManager.GetString("ThisNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide timeline.
        /// </summary>
        public static string TimelineShowHide {
            get {
                return ResourceManager.GetString("TimelineShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining.
        /// </summary>
        public static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to create a project, click New..
        /// </summary>
        public static string ToCreateProjectClickNew {
            get {
                return ResourceManager.GetString("ToCreateProjectClickNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Notes.
        /// </summary>
        public static string UpdateNote {
            get {
                return ResourceManager.GetString("UpdateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use automatic backups.
        /// </summary>
        public static string UseAutoBackup {
            get {
                return ResourceManager.GetString("UseAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current frame.
        /// </summary>
        public static string UseCurrentFrame {
            get {
                return ResourceManager.GetString("UseCurrentFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dark mode.
        /// </summary>
        public static string UseDarkMode {
            get {
                return ResourceManager.GetString("UseDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the GPU for image processing.
        /// </summary>
        public static string UsingGPUForImageProcessing {
            get {
                return ResourceManager.GetString("UsingGPUForImageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file.
        /// </summary>
        public static string VideoFile {
            get {
                return ResourceManager.GetString("VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video output.
        /// </summary>
        public static string VideoOutput {
            get {
                return ResourceManager.GetString("VideoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you close the application, the changes will begin..
        /// </summary>
        public static string WhenYouCloseTheApplicationTheChangesWillBegin {
            get {
                return ResourceManager.GetString("WhenYouCloseTheApplicationTheChangesWillBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of 1 frame.
        /// </summary>
        public static string WidthOf1Frame {
            get {
                return ResourceManager.GetString("WidthOf1Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
    }
}
