namespace Beutl.Graphics.Rendering;

internal enum ExecutionIslandBoundaryReason : byte
{
    MaterializedInput,
    CoverageResolution,
    WholeSourceShader,
    Geometry,
    Opaque,
    CustomEffectItem,
    TargetCommand,
    TargetCapture,
    TargetScope,
    Layer,
    Readback,
    UnsafeComposite,
    SemanticComposite,
    RawCanvas,
    CacheInput,
    CacheCapture,
    BackendTransition,
    ThreeD,
    DynamicTopology,
    ScopeMismatch,
    ScaleTransition,
    Branching,
    FusionDisabled,
    BackendLimit,
    FilterEffectSegment,
}
