//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Properties.CommandLineResources", typeof(CommandLineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Create a new project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the project file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToLoadProject {
            get {
                return ResourceManager.GetString("FailedToLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpeg was not found. Do you want to install it? (Y/N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FFmpegNotFound {
            get {
                return ResourceManager.GetString("FFmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame to output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FrameToOutput {
            get {
                return ResourceManager.GetString("FrameToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsDownloading {
            get {
                return ResourceManager.GetString("IsDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is extracted and placed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsExtractedAndPlaced {
            get {
                return ResourceManager.GetString("IsExtractedAndPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is loading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IsLoading {
            get {
                return ResourceManager.GetString("IsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of new project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameOfProject {
            get {
                return ResourceManager.GetString("NameOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output destination file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputDestinationFile {
            get {
                return ResourceManager.GetString("OutputDestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output the project in Json format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputProjectToJson {
            get {
                return ResourceManager.GetString("OutputProjectToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output the scene to video. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputVideo {
            get {
                return ResourceManager.GetString("OutputVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the specified frame of the scene as an image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFrameToImageFile {
            get {
                return ResourceManager.GetString("SaveFrameToImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame to scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SceneToOutput {
            get {
                return ResourceManager.GetString("SceneToOutput", resourceCulture);
            }
        }
    }
}
