//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.PackageTools.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.PackageTools.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Accept all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AcceptAll {
            get {
                return ResourceManager.GetString("AcceptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acceptance of License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Acceptance_of_License {
            get {
                return ResourceManager.GetString("Acceptance_of_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close this window because other Beutl.PackageTools processes are running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close_this_window_because_other_Beutl_PackageTools_processes_are_running {
            get {
                return ResourceManager.GetString("Close_this_window_because_other_Beutl_PackageTools_processes_are_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete unnecessary packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete_unnecessary_packages {
            get {
                return ResourceManager.GetString("Delete_unnecessary_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted unnecessary packages. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Deleted_unnecessary_packages {
            get {
                return ResourceManager.GetString("Deleted_unnecessary_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Deleting_files {
            get {
                return ResourceManager.GetString("Deleting_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting unnecessary packages... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Deleting_unnecessary_packages {
            get {
                return ResourceManager.GetString("Deleting_unnecessary_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to continue with the installation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do_you_really_want_to_continue_with_the_installation {
            get {
                return ResourceManager.GetString("Do_you_really_want_to_continue_with_the_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to use this package? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do_you_want_to_use_this_package {
            get {
                return ResourceManager.GetString("Do_you_want_to_use_this_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloaded &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Downloaded_XXX {
            get {
                return ResourceManager.GetString("Downloaded_XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading &apos;{0}&apos;... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Downloading_XXX {
            get {
                return ResourceManager.GetString("Downloading_XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash code verification failed.
        ///This package file may have been tampered with. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hash_code_verification_failed {
            get {
                return ResourceManager.GetString("Hash_code_verification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Operation_canceled {
            get {
                return ResourceManager.GetString("Operation_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Package with same ID found in local source. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Package_with_same_ID_found_in_local_source {
            get {
                return ResourceManager.GetString("Package_with_same_ID_found_in_local_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please accept the following license. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Please_accept_the_following_license {
            get {
                return ResourceManager.GetString("Please_accept_the_following_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolve dependencies に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResolveDependencies {
            get {
                return ResourceManager.GetString("ResolveDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the packages to be deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Select_the_packages_to_be_deleted {
            get {
                return ResourceManager.GetString("Select_the_packages_to_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skipped downloading to use local source. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Skipped_downloading_to_use_local_source {
            get {
                return ResourceManager.GetString("Skipped_downloading_to_use_local_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skipped verification because local source is used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Skipped_verification_because_local_source_is_used {
            get {
                return ResourceManager.GetString("Skipped_verification_because_local_source_is_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Succeeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no licenses that require acceptance. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string There_are_no_licenses_that_require_acceptance {
            get {
                return ResourceManager.GetString("There_are_no_licenses_that_require_acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These packages were not deleted successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string These_packages_were_not_deleted_successfully {
            get {
                return ResourceManager.GetString("These_packages_were_not_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This package has already been uninstalled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string This_package_has_already_been_uninstalled {
            get {
                return ResourceManager.GetString("This_package_has_already_been_uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstalled &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Uninstalled_XXX {
            get {
                return ResourceManager.GetString("Uninstalled_XXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying hash code... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerifyingHashCode {
            get {
                return ResourceManager.GetString("VerifyingHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for all Beutl processes to terminate... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Waiting_for_all_Beutl_processes_to_terminate {
            get {
                return ResourceManager.GetString("Waiting_for_all_Beutl_processes_to_terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} has been released. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XXX_has_been_released {
            get {
                return ResourceManager.GetString("XXX_has_been_released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} will be released. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XXX_will_be_released {
            get {
                return ResourceManager.GetString("XXX_will_be_released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
