//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Extensions.FFmpeg.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.Extensions.FFmpeg.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FFmpeg Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FFmpegError {
            get {
                return ResourceManager.GetString("FFmpegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make sure you have FFmpeg installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Make_sure_you_have_FFmpeg_installed {
            get {
                return ResourceManager.GetString("Make_sure_you_have_FFmpeg_installed", resourceCulture);
            }
        }

        public static string Install
        {
            get
            {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }

        /// <summary>
        ///   Install FFmpeg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Install_FFmpeg {
            get {
                return ResourceManager.GetString("Install_FFmpeg", resourceCulture);
            }
        }

        /// <summary>
        ///   Preparing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }

        /// <summary>
        ///   Fetching release information... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fetching_release_information {
            get {
                return ResourceManager.GetString("Fetching_release_information", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to find FFmpeg release. Unsupported platform or network error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed_to_find_FFmpeg_release {
            get {
                return ResourceManager.GetString("Failed_to_find_FFmpeg_release", resourceCulture);
            }
        }

        /// <summary>
        ///   Installation complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installation_complete {
            get {
                return ResourceManager.GetString("Installation_complete", resourceCulture);
            }
        }

        /// <summary>
        ///   Installing FFmpeg via Homebrew... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installing_FFmpeg_via_Homebrew {
            get {
                return ResourceManager.GetString("Installing_FFmpeg_via_Homebrew", resourceCulture);
            }
        }

        /// <summary>
        ///   Homebrew not found. Please install Homebrew first: https://brew.sh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homebrew_not_found {
            get {
                return ResourceManager.GetString("Homebrew_not_found", resourceCulture);
            }
        }

        /// <summary>
        ///   Installation failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installation_failed {
            get {
                return ResourceManager.GetString("Installation_failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Failed to run Homebrew: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed_to_run_Homebrew {
            get {
                return ResourceManager.GetString("Failed_to_run_Homebrew", resourceCulture);
            }
        }

        /// <summary>
        ///   Download FFmpeg 8.0 from BtbN/FFmpeg-Builds (GitHub) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download_FFmpeg_from_BtbN {
            get {
                return ResourceManager.GetString("Download_FFmpeg_from_BtbN", resourceCulture);
            }
        }

        /// <summary>
        ///   Install FFmpeg 8.0 using Homebrew (brew install ffmpeg@8) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Install_FFmpeg_using_Homebrew {
            get {
                return ResourceManager.GetString("Install_FFmpeg_using_Homebrew", resourceCulture);
            }
        }

        /// <summary>
        ///   Unknown method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unknown_method {
            get {
                return ResourceManager.GetString("Unknown_method", resourceCulture);
            }
        }
    }
}
