//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Extensions.FFmpeg.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Beutl.Extensions.FFmpeg.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FFmpegError {
            get {
                return ResourceManager.GetString("FFmpegError", resourceCulture);
            }
        }
        
        public static string Make_sure_you_have_FFmpeg_installed {
            get {
                return ResourceManager.GetString("Make_sure_you_have_FFmpeg_installed", resourceCulture);
            }
        }
        
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        public static string Install_FFmpeg {
            get {
                return ResourceManager.GetString("Install_FFmpeg", resourceCulture);
            }
        }
        
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        public static string Fetching_release_information {
            get {
                return ResourceManager.GetString("Fetching_release_information", resourceCulture);
            }
        }
        
        public static string Failed_to_find_FFmpeg_release {
            get {
                return ResourceManager.GetString("Failed_to_find_FFmpeg_release", resourceCulture);
            }
        }
        
        public static string Installation_complete {
            get {
                return ResourceManager.GetString("Installation_complete", resourceCulture);
            }
        }
        
        public static string Installing_FFmpeg_via_Homebrew {
            get {
                return ResourceManager.GetString("Installing_FFmpeg_via_Homebrew", resourceCulture);
            }
        }
        
        public static string Homebrew_not_found {
            get {
                return ResourceManager.GetString("Homebrew_not_found", resourceCulture);
            }
        }
        
        public static string Installation_failed {
            get {
                return ResourceManager.GetString("Installation_failed", resourceCulture);
            }
        }
        
        public static string Failed_to_run_Homebrew {
            get {
                return ResourceManager.GetString("Failed_to_run_Homebrew", resourceCulture);
            }
        }
        
        public static string Download_FFmpeg_from_BtbN {
            get {
                return ResourceManager.GetString("Download_FFmpeg_from_BtbN", resourceCulture);
            }
        }
        
        public static string Install_FFmpeg_using_Homebrew {
            get {
                return ResourceManager.GetString("Install_FFmpeg_using_Homebrew", resourceCulture);
            }
        }
        
        public static string Unknown_method {
            get {
                return ResourceManager.GetString("Unknown_method", resourceCulture);
            }
        }
        
        public static string Verifying_FFmpeg_installation {
            get {
                return ResourceManager.GetString("Verifying_FFmpeg_installation", resourceCulture);
            }
        }
        
        public static string FFmpeg_installation_successful {
            get {
                return ResourceManager.GetString("FFmpeg_installation_successful", resourceCulture);
            }
        }
        
        public static string FFmpeg_verification_failed {
            get {
                return ResourceManager.GetString("FFmpeg_verification_failed", resourceCulture);
            }
        }
        
        public static string Installing_Homebrew {
            get {
                return ResourceManager.GetString("Installing_Homebrew", resourceCulture);
            }
        }
        
        public static string Homebrew_not_found_installing {
            get {
                return ResourceManager.GetString("Homebrew_not_found_installing", resourceCulture);
            }
        }
        
        public static string Homebrew_installation_failed {
            get {
                return ResourceManager.GetString("Homebrew_installation_failed", resourceCulture);
            }
        }
        
        public static string Homebrew_not_found_after_installation {
            get {
                return ResourceManager.GetString("Homebrew_not_found_after_installation", resourceCulture);
            }
        }
        
        public static string Failed_to_install_Homebrew {
            get {
                return ResourceManager.GetString("Failed_to_install_Homebrew", resourceCulture);
            }
        }
        
        public static string FFmpegEncoder {
            get {
                return ResourceManager.GetString("FFmpegEncoder", resourceCulture);
            }
        }
        
        public static string FFmpegDecoder {
            get {
                return ResourceManager.GetString("FFmpegDecoder", resourceCulture);
            }
        }
    }
}
