//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Primitive.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Primitive.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adjust coordinates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdjustCoordinates {
            get {
                return ResourceManager.GetString("AdjustCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anchors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Anchors {
            get {
                return ResourceManager.GetString("Anchors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Angle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area expansion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaExpansion {
            get {
                return ResourceManager.GetString("AreaExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ball に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ball {
            get {
                return ResourceManager.GetString("Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binarization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Binarization {
            get {
                return ResourceManager.GetString("Binarization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blur に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Blur {
            get {
                return ResourceManager.GetString("Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness correction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightnessCorrection {
            get {
                return ResourceManager.GetString("BrightnessCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CenterX {
            get {
                return ResourceManager.GetString("CenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CenterY {
            get {
                return ResourceManager.GetString("CenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chroma key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChromaKey {
            get {
                return ResourceManager.GetString("ChromaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Circular gradient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CircularGradient {
            get {
                return ResourceManager.GetString("CircularGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clamp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clamp {
            get {
                return ResourceManager.GetString("Clamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear the frame buffer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearFramebuffer {
            get {
                return ResourceManager.GetString("ClearFramebuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Clipping {
            get {
                return ResourceManager.GetString("Clipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorKey {
            get {
                return ResourceManager.GetString("ColorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contrast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contrast correction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContrastCorrection {
            get {
                return ResourceManager.GetString("ContrastCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coordinate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cube に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cube {
            get {
                return ResourceManager.GetString("Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Decal {
            get {
                return ResourceManager.GetString("Decal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depth function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DepthFunction {
            get {
                return ResourceManager.GetString("DepthFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depth test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DepthTest {
            get {
                return ResourceManager.GetString("DepthTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Depth Testing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DepthTestEnable {
            get {
                return ResourceManager.GetString("DepthTestEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diffusion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Diffusion {
            get {
                return ResourceManager.GetString("Diffusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dilate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dilate {
            get {
                return ResourceManager.GetString("Dilate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropShadow {
            get {
                return ResourceManager.GetString("DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ellipse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable multiple objects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnableMultipleObjects {
            get {
                return ResourceManager.GetString("EnableMultipleObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Erode {
            get {
                return ResourceManager.GetString("Erode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} failed to load. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to original size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FitToOriginalSize {
            get {
                return ResourceManager.GetString("FitToOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   viewing angle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fov {
            get {
                return ResourceManager.GetString("Fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Framebuffer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Framebuffer {
            get {
                return ResourceManager.GetString("Framebuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frequency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gamma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Gamma {
            get {
                return ResourceManager.GetString("Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gamma correction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GammaCorrection {
            get {
                return ResourceManager.GetString("GammaCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3D object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GL3DObject {
            get {
                return ResourceManager.GetString("GL3DObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grayscale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Grayscale {
            get {
                return ResourceManager.GetString("Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HorizontalAlignment {
            get {
                return ResourceManager.GetString("HorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageEffects {
            get {
                return ResourceManager.GetString("ImageEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image splitting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplit {
            get {
                return ResourceManager.GetString("ImageSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invert Mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvertMask {
            get {
                return ResourceManager.GetString("InvertMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liear gradient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinearGradient {
            get {
                return ResourceManager.GetString("LinearGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line spacing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineSpacing {
            get {
                return ResourceManager.GetString("LineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   line width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineWidth {
            get {
                return ResourceManager.GetString("LineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listener に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Listener {
            get {
                return ResourceManager.GetString("Listener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mirror に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monochromatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Monoc {
            get {
                return ResourceManager.GetString("Monoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple Image Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MultipleImageControls {
            get {
                return ResourceManager.GetString("MultipleImageControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Negaposi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Negaposi {
            get {
                return ResourceManager.GetString("Negaposi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Noise {
            get {
                return ResourceManager.GetString("Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of horizontal divisions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberOfHorizontalDivisions {
            get {
                return ResourceManager.GetString("NumberOfHorizontalDivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of vertical divisions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberOfVerticalDivisions {
            get {
                return ResourceManager.GetString("NumberOfVerticalDivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path to the image object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathToImageObject {
            get {
                return ResourceManager.GetString("PathToImageObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perspective に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Perspective {
            get {
                return ResourceManager.GetString("Perspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point light diffuse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PointLightDiffuse {
            get {
                return ResourceManager.GetString("PointLightDiffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point light source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PointLightSource {
            get {
                return ResourceManager.GetString("PointLightSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polygon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radius に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RGB correction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RGBColorCorrection {
            get {
                return ResourceManager.GetString("RGBColorCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round rect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoundRect {
            get {
                return ResourceManager.GetString("RoundRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scenes {
            get {
                return ResourceManager.GetString("Scenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sepia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sepia {
            get {
                return ResourceManager.GetString("Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetX {
            get {
                return ResourceManager.GetString("TargetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetY {
            get {
                return ResourceManager.GetString("TargetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetZ {
            get {
                return ResourceManager.GetString("TargetZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThresholdValue {
            get {
                return ResourceManager.GetString("ThresholdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerticalAlignment {
            get {
                return ResourceManager.GetString("VerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VideoFile {
            get {
                return ResourceManager.GetString("VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Xor {
            get {
                return ResourceManager.GetString("Xor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZFar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZFar {
            get {
                return ResourceManager.GetString("ZFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZNear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZNear {
            get {
                return ResourceManager.GetString("ZNear", resourceCulture);
            }
        }
    }
}
