//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add a new clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddClip {
            get {
                return ResourceManager.GetString("AddClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a new effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddEffect {
            get {
                return ResourceManager.GetString("AddEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add gradient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddGradient {
            get {
                return ResourceManager.GetString("AddGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Additive {
            get {
                return ResourceManager.GetString("Additive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a keyframe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddKeyframe {
            get {
                return ResourceManager.GetString("AddKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alpha blend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlphaBlend {
            get {
                return ResourceManager.GetString("AlphaBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ambient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ambient {
            get {
                return ResourceManager.GetString("Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bind the value of the property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BindCommand {
            get {
                return ResourceManager.GetString("BindCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CenterX {
            get {
                return ResourceManager.GetString("CenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CenterY {
            get {
                return ResourceManager.GetString("CenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CenterZ {
            get {
                return ResourceManager.GetString("CenterZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change easing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeEasing {
            get {
                return ResourceManager.GetString("ChangeEasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeFile {
            get {
                return ResourceManager.GetString("ChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeFolder {
            get {
                return ResourceManager.GetString("ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change gradient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeGradient {
            get {
                return ResourceManager.GetString("ChangeGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the state of the checkbox に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeIsChecked {
            get {
                return ResourceManager.GetString("ChangeIsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeLength {
            get {
                return ResourceManager.GetString("ChangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change selected item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeSelectItem {
            get {
                return ResourceManager.GetString("ChangeSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeValue {
            get {
                return ResourceManager.GetString("ChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child elements not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChildElementsNotFound {
            get {
                return ResourceManager.GetString("ChildElementsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coordinate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diffuse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Diffuse {
            get {
                return ResourceManager.GetString("Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect property value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the order of the effects (below) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownEffect {
            get {
                return ResourceManager.GetString("DownEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable/Disable effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnableDisableEffect {
            get {
                return ResourceManager.GetString("EnableDisableEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to convert value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToConvertValue {
            get {
                return ResourceManager.GetString("FailedToConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} failed to load. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to remove. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToRemove {
            get {
                return ResourceManager.GetString("FailedToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The keyframe has been moved out of range.
        ///{0} -&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyframeHasBeenMovedOutOfRange {
            get {
                return ResourceManager.GetString("KeyframeHasBeenMovedOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This key has already been registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyHasAlreadyBeenRegisterd {
            get {
                return ResourceManager.GetString("KeyHasAlreadyBeenRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message by {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBy {
            get {
                return ResourceManager.GetString("MessageBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoveClip {
            get {
                return ResourceManager.GetString("MoveClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move keyframe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoveKeyframe {
            get {
                return ResourceManager.GetString("MoveKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiplication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Multiplication {
            get {
                return ResourceManager.GetString("Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent element not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParentElementNotFound {
            get {
                return ResourceManager.GetString("ParentElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Primitive {
            get {
                return ResourceManager.GetString("Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveClip {
            get {
                return ResourceManager.GetString("RemoveClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveEffect {
            get {
                return ResourceManager.GetString("RemoveEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove gradient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveGradient {
            get {
                return ResourceManager.GetString("RemoveGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove keyframe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveKeyframe {
            get {
                return ResourceManager.GetString("RemoveKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveLayer {
            get {
                return ResourceManager.GetString("RemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveTarget {
            get {
                return ResourceManager.GetString("RemoveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RotateX {
            get {
                return ResourceManager.GetString("RotateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RotateY {
            get {
                return ResourceManager.GetString("RotateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RotateZ {
            get {
                return ResourceManager.GetString("RotateZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shininess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shininess {
            get {
                return ResourceManager.GetString("Shininess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specular に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Specular {
            get {
                return ResourceManager.GetString("Specular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split a clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SplitClip {
            get {
                return ResourceManager.GetString("SplitClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type of the owner of the property does not match the type of this object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TheOwnerTypeDoesNotMatch {
            get {
                return ResourceManager.GetString("TheOwnerTypeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value was not {0} type, but {1} type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TheValueWasNotTypeButType {
            get {
                return ResourceManager.GetString("TheValueWasNotTypeButType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update the position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatePosition {
            get {
                return ResourceManager.GetString("UpdatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the order of the effects (top) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpEffect {
            get {
                return ResourceManager.GetString("UpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
