//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEditor.Core.Command {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandName() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEditor.Core.Command.CommandName", typeof(CommandName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add a clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddClip {
            get {
                return ResourceManager.GetString("AddClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddEffect {
            get {
                return ResourceManager.GetString("AddEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a keyframe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddKeyFrame {
            get {
                return ResourceManager.GetString("AddKeyFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bind the value of the property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BindCommand {
            get {
                return ResourceManager.GetString("BindCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change easing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeEasing {
            get {
                return ResourceManager.GetString("ChangeEasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeFile {
            get {
                return ResourceManager.GetString("ChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeFolder {
            get {
                return ResourceManager.GetString("ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the state of the checkbox に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeIsChecked {
            get {
                return ResourceManager.GetString("ChangeIsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeLength {
            get {
                return ResourceManager.GetString("ChangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change selected item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeSelectItem {
            get {
                return ResourceManager.GetString("ChangeSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeValue {
            get {
                return ResourceManager.GetString("ChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect property value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the order of the effects (below) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownEffect {
            get {
                return ResourceManager.GetString("DownEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable/Disable effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableDisableEffect {
            get {
                return ResourceManager.GetString("EnableDisableEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveClip {
            get {
                return ResourceManager.GetString("MoveClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move keyframe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveKeyFrame {
            get {
                return ResourceManager.GetString("MoveKeyFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveClip {
            get {
                return ResourceManager.GetString("RemoveClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveEffect {
            get {
                return ResourceManager.GetString("RemoveEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove keyframe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveKeyFrame {
            get {
                return ResourceManager.GetString("RemoveKeyFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveLayer {
            get {
                return ResourceManager.GetString("RemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split a clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplitClip {
            get {
                return ResourceManager.GetString("SplitClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the order of the effects (top) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpEffect {
            get {
                return ResourceManager.GetString("UpEffect", resourceCulture);
            }
        }
    }
}
