global using Nuke.Common;
global using Nuke.Common.CI;
global using static Nuke.Common.EnvironmentInfo;
global using Nuke.Common.Execution;
global using Nuke.Common.Git;
global using Nuke.Common.IO;
global using static Nuke.Common.IO.PathConstruction;
global using Nuke.Common.ProjectModel;
global using Nuke.Common.Tooling;
global using static Nuke.Common.Tooling.ProcessTasks;
global using Nuke.Common.Tools.DotNet;
global using static Nuke.Common.Tools.DotNet.DotNetTasks;
global using Nuke.Common.Tools.GitVersion;
global using Nuke.Common.Tools.MSBuild;
global using static Nuke.Common.Tools.MSBuild.MSBuildTasks;
global using Nuke.Common.Utilities.Collections;
