<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="System.Management" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Beutl.Core\Beutl.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Beutl" />
    <InternalsVisibleTo Include="Beutl.HeadlessUITests" />
  </ItemGroup>
</Project>
