name: Daily build
on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
  workflow_dispatch:

jobs:
  skia-native:
    uses: ./.github/workflows/build-skia-native.yml
    with:
      artifact-prefix: daily-skia-native

  determine-version:
    uses: ./.github/workflows/build-version.yml

  daily-build:
    needs: [determine-version, skia-native]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux_x64, win_x64, win_arm64, osx_x64, osx_arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
        persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        global-json-file: global.json

    - name: Download libSkiaSharp
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: daily-skia-native-*
        path: native/SkiaSharp/artifacts
        merge-multiple: true

    - name: Restore
      run: |
        chmod +x build.sh
        ./build.sh restore --runtime ${{ matrix.rid }}

    - name: Build
      run: |
        ./build.sh publish \
          --runtime ${{ matrix.rid }} \
          --skip restore \
          --version ${{ needs.determine-version.outputs.nugetVer }} \
          --assembly-version ${{ needs.determine-version.outputs.asmVer }} \
          --informational-version ${{ needs.determine-version.outputs.infoVer }}

    - name: Zip
      run: |
        ./build.sh zip \
          --runtime ${{ matrix.rid }} \
          --skip publish \
          --version ${{ needs.determine-version.outputs.nugetVer }}

    - name: Save
      uses: actions/upload-artifact@v7
      with:
        name: beutl_${{ matrix.rid }}
        path: ./artifacts/
