name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read
      code-quality: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore Beutl.slnx

      - name: Build
        run: dotnet build Beutl.slnx --no-restore

      - name: Test
        run: dotnet test Beutl.slnx --no-build --verbosity normal -f net10.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings

      - name: Generate Report
        run: reportgenerator -reports:'tests/**/coverage.cobertura.xml' -targetdir:coveragereport -reporttypes:'Html;Cobertura'

      - name: Save
        uses: actions/upload-artifact@v7
        with:
          name: Coverage
          path: coveragereport

      - name: Upload coverage to GitHub Code Quality
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          report: coveragereport/Cobertura.xml
          language: CSharp
          label: code-coverage/dotnet
