name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore Beutl.slnx

      - name: Build
        run: dotnet build Beutl.slnx --no-restore -f net9.0

      - name: Test
        run: dotnet test Beutl.slnx --no-build --verbosity normal -f net9.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: tests/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '0 80'
#          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        continue-on-error: true
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Generate Report
        run: reportgenerator -reports:`find tests/Beutl.UnitTests/TestResults/*/coverage.cobertura.xml | head -n 1 ` -targetdir:coveragereport -reporttypes:Html

      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Coverage
          path: coveragereport
