name: Debug Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: nuget-v2-${{ runner.os }}-${{ matrix.dotnet-version }} # v2がついているのは容量オーバー対策
        restore-keys: |
          nuget-v2-${{ runner.os }}-
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore BEditor.sln

    - name: Build
      run: dotnet build BEditor.sln -property:DefineConstants=GITHUB_ACTIONS

    - name: Test
      run: dotnet test BEditor.sln --no-build --verbosity normal

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: binary-${{ runner.os }}
        path: ./src/executable/BEditor.Avalonia/bin/Debug/net6.0
