name: Japanese Release Notes Dispatcher

on:
  discussion:
    types: [created]

jobs:
  dispatch:
    if: |
      startsWith(github.event.discussion.title, 'v') &&
      contains(github.event.discussion.title, '.')
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger translation workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run translate-release-notes.yml \
            -R ${{ github.repository }} \
            --ref main \
            -f discussion_number='${{ github.event.discussion.number }}' \
            -f discussion_node_id='${{ github.event.discussion.node_id }}' \
            -f discussion_title='${{ github.event.discussion.title }}' \
            -f discussion_html_url='${{ github.event.discussion.html_url }}'
